# This playbook is to configure MongoDB in our db server  
---
# host name
- hosts: db

  gather_facts: yes

# admin access
  become: yes

# add set of instructions
  tasks:
  - name: Set up MongoDB in db server
    apt: pkg=mongodb state=present

  - name: Remove mongod.conf file
    file:
      path: /etc/mongodb.conf
      state: absent

  - name: Touch a file
    file:
      path: /etc/mongodb.conf
      state: touch
      mode: u=rw,g=r,o=r

  - name: Insert multiple lines and backup
    blockinfile:
      path: /etc/mongodb.conf
      backup: yes
      block: |
        "storage:
          dbPath: /var/lib/mongodb
          journal:
            enabled: true
        systemLog:
          destination: file
          logAppend: true
          path: /var/log/mongodb/mongod.log
        net:
          port: 27017
          bindIp:0.0.0.0"